-- Round-trip fix for CP775-mangled UTF-8 in Supabase seed
-- Generated automatically from observed mojibake patterns
BEGIN;

UPDATE categories SET name = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(name, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE name IS NOT NULL;
UPDATE municipalities SET name = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(name, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE name IS NOT NULL;
UPDATE municipalities SET short_description = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(short_description, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE short_description IS NOT NULL;
UPDATE places SET name = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(name, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE name IS NOT NULL;
UPDATE places SET subtype = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(subtype, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE subtype IS NOT NULL;
UPDATE places SET short_description = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(short_description, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE short_description IS NOT NULL;
UPDATE places SET long_description = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(long_description, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE long_description IS NOT NULL;
UPDATE places SET accessibility_notes = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(accessibility_notes, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE accessibility_notes IS NOT NULL;
UPDATE places SET beach_type = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(beach_type, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE beach_type IS NOT NULL;
UPDATE place_images SET alt_text = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(alt_text, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE alt_text IS NOT NULL;
UPDATE place_images SET credit = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(credit, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE credit IS NOT NULL;
UPDATE place_images SET license_label = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(license_label, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é') WHERE license_label IS NOT NULL;

-- JSONB array columns on places: alternate_names, tags, amenities, best_for
-- Cast to text, run all replaces, cast back. Simpler than unnesting.
UPDATE places SET alternate_names = (replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(alternate_names::text, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é'))::jsonb WHERE alternate_names IS NOT NULL;
UPDATE places SET tags = (replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(tags::text, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é'))::jsonb WHERE tags IS NOT NULL;
UPDATE places SET amenities = (replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(amenities::text, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é'))::jsonb WHERE amenities IS NOT NULL;
UPDATE places SET best_for = (replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(best_for::text, '┼Ī', 'š'), '─ć', 'ć'), '┼Š', 'ž'), '─Ź', 'č'), '┼Į', 'Ž'), '┼Ā', 'Š'), '─å', 'Ć'), '─ī', 'Č'), '─æ', 'đ'), '┬Ā', ' '), '├½', 'ë'), '─É', 'Đ'), '├¦', 'ç'), '├®', 'é'))::jsonb WHERE best_for IS NOT NULL;

-- Re-fire the full-text trigger so search_document reflects fixed content
UPDATE places SET name = name;
COMMIT;
